spring:
  application:
    name: power-scheduler-worker-sample-springboot

server:
  port: 9999

power-scheduler-worker:
  enabled: ${POWER_SCHEDULER_WORKER_ENABLED:true}
  app-code: ${POWER_SCHEDULER_WORKER_APP_CODE:}
  # app-secret从控制台页面获取
  app-secret: ${POWER_SCHEDULER_WORKER_APP_SECRET:}
  server-endpoint: ${POWER_SCHEDULER_WORKER_SERVER_ENDPOINTS:127.0.0.1:8080}
  port: ${POWER_SCHEDULER_WORKER_PORT:7758}
  # 如果服务部署在docker且使用bridge模式做了端口映射，则需要配置external-host为宿主机的ip，external-port为映射到宿主机上的端口
#  external-host: ${POWER_SCHEDULER_WORKER_EXTERNAL_HOST:}
#  external-port: ${POWER_SCHEDULER_WORKER_EXTERNAL_PORT:}

