name: Docker Image For Trial CI

on:
  push:
    branches:
      - docker/trial_image

  workflow_dispatch:

jobs:

  build-and-push-docker-image:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582

      - name: BuildJar with Gradle
        run: ./gradlew bootJar shadowJar --no-daemon

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Aliyun Container Registry
        uses: docker/login-action@v2
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_CONTAINER_REGISTRY_PASSWORD }}

      - name: Build and push multi-arch image for server
        uses: docker/build-push-action@v4
        with:
          file: ./power-scheduler-server/Dockerfile
          context: ./power-scheduler-server
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            registry.cn-hangzhou.aliyuncs.com/wcz-docker-repo/power-scheduler-server:trial

      - name: Build and push multi-arch image for springboot sample
        uses: docker/build-push-action@v4
        with:
          file: ./power-scheduler-worker-sample/power-scheduler-worker-sample-springboot/Dockerfile
          context: ./power-scheduler-worker-sample/power-scheduler-worker-sample-springboot
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            registry.cn-hangzhou.aliyuncs.com/wcz-docker-repo/power-scheduler-worker-sample-springboot:trial

      - name: Build and push multi-arch image for frameless sample
        uses: docker/build-push-action@v4
        with:
          file: ./power-scheduler-worker-sample/power-scheduler-worker-sample-frameless/Dockerfile
          context: ./power-scheduler-worker-sample/power-scheduler-worker-sample-frameless
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            registry.cn-hangzhou.aliyuncs.com/wcz-docker-repo/power-scheduler-worker-sample-frameless:trial
           
