name: Docker Image For Mysql CI

on:
  push:
    branches: [ "docker/mysql_image" ]
  pull_request:
    branches: [ "docker/mysql_image" ]

  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Image tag'
        required: true
        default: 'latest-mysql'

jobs:

  build-and-push:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push multi-arch image
        uses: docker/build-push-action@v4
        with:
          file: ./power-scheduler-server/Dockerfile
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: 771592594/power-scheduler-server:${{ inputs.image_tag || 'latest-mysql' }}
