name: Docker Image For Worker Sample CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Image tag'
        required: true
        default: 'latest'

jobs:

  build-and-push:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push multi-arch image for springboot sample
        uses: docker/build-push-action@v4
        with:
          file: ./power-scheduler-worker-sample/power-scheduler-worker-sample-springboot/Dockerfile
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: 771592594/power-scheduler-worker-sample-springboot:${{ inputs.image_tag || 'latest' }}

      - name: Build and push multi-arch image for frameless sample
        uses: docker/build-push-action@v4
        with:
          file: ./power-scheduler-worker-sample/power-scheduler-worker-sample-frameless/Dockerfile
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: 771592594/power-scheduler-worker-sample-frameless:${{ inputs.image_tag || 'latest' }}
